name: Tomcat Server Health Check

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-servers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current date and time
        id: get_datetime
        run: |
          echo "current_datetime=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Ping servers and log status
        id: check_servers
        run: |
          DOWN_SERVERS=""
          LOG_FILE="server_status_${{ env.current_datetime }}.log"
          echo "Server Status Log - $(date)" > $LOG_FILE
          while IFS= read -r server; do
            if ping -c 1 -W 5 "$server" &>/dev/null; then
              echo "$server - UP" >> $LOG_FILE
            else
              echo "$server - DOWN" >> $LOG_FILE
              DOWN_SERVERS="$DOWN_SERVERS$server\n"
            fi
          done < servers.list
          echo "down_servers=$DOWN_SERVERS" >> $GITHUB_ENV
          echo "log_file=$LOG_FILE" >> $GITHUB_ENV

      - name: Commit and push server status log
        if: always()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ${{ env.log_file }}
          git commit -m "Add server status log for ${{ env.current_datetime }}"
          git push

