name: Tomcat Server Health Check

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  check-servers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ping servers and check status
        id: check_servers
        run: |
          DOWN_SERVERS=""
          while IFS= read -r server; do
            if ! ping -c 1 -W 5 "$server" &>/dev/null; then
              DOWN_SERVERS="$DOWN_SERVERS$server\n"
            fi
          done < servers.list
          echo "down_servers=$DOWN_SERVERS" >> $GITHUB_ENV
